export const COUNTRIES_REQUEST_PENDING = 'COUNTRIES_REQUEST_PENDING';
export const COUNTRIES_REQUEST_SUCCESS = 'COUNTRIES_REQUEST_SUCCESS';
export const COUNTRIES_REQUEST_FAILED = 'COUNTRIES_REQUEST_FAILED';
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';