export const COUNTRIES_REQUEST_PENDING = 'COUNTRIES_REQUEST_PENDING';
export const COUNTRIES_REQUEST_SUCCESS = 'COUNTRIES_REQUEST_SUCCESS';
export const COUNTRIES_REQUEST_FAILED = 'COUNTRIES_REQUEST_FAILED';
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';
export const SEARCH_COUNTRIES = 'SEARCH_COUNTRIES';
export const FILTER_COUNTRIES = 'FILTER_COUNTRIES';
export const EMPTY_SEARCH_FIELD = 'EMPTY_SEARCH_FIELD';